version: '3'
services:
    store-nginx:
        build:
            context: ./store/docker/dev
            dockerfile: nginx.docker
        volumes:
            - ./store:/app
        depends_on:
            - store-php-fpm
        ports:
            - "8080:80"

    store-php-fpm:
        build:
            context: ./store/docker/dev
            dockerfile: php-fpm.docker
        volumes:
            - ./store:/app
        depends_on:
            - store-mysql
            - store-storage
            - store-mailer

    store-php-cli:
        build:
            context: ./store/docker/dev
            dockerfile: php-cli.docker
        volumes:
            - ./store:/app
            - composer:/root/.composer/cache
        depends_on:
            - store-mysql
            - store-storage
            - store-mailer
        tty: true

    store-mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: app
            MYSQL_ROOT_PASSWORD: secret

    store-mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"

    store-storage:
        build:
            context: ./store/docker/dev
            dockerfile: nginx.docker
        volumes:
            - ./storage:/app
        ports:
            - "8081:80"

    store-storage-ftp:
        image: stilliard/pure-ftpd
        environment:
            FTP_USER_NAME: app
            FTP_USER_PASS: secret
            FTP_USER_HOME: /app
        volumes:
            - ./storage/public:/app

volumes:
    storage-mysql:
    composer: